day1:
	@echo "--- day 1 solution ---"
	@echo "--- part 1 ---"
	@cd 1/part1/ && go run main.go
	@echo ""
	@echo "--- part 2 ---"
	@cd 1/part2 && go run main.go

day2:
	@echo "--- day 2 solution ---"
	@echo "--- part 1 ---"
	@cd 2/part1/ && go run main.go
	@echo ""
	@echo "--- part 2 ---"
	@cd 2/part2 && go run main.go

day3:
	@echo "--- day 3 solution ---"
	@echo "--- part 1 ---"
	@cd 3/part1/ && go run main.go
	@echo ""
	@echo "--- part 2 ---"
	@cd 3/part2 && go run main.go


